### ISSUE TITLE
where windows 11 dark mode wallpaper sussy

### ISSUE THREAD

**Issue by bedantadey17** [Amog-OS/AmogOS-Wallpapers#7]
sus

**Comment by BeauTheBeau** [comment]
![image](https://github.com/Amog-OS/AmogOS-Wallpapers/assets/90942493/02eb0cb0-eec0-4a01-8362-528eef643361)

^ Made by @NazagamerITA ([Discord](1058323637993750569))

**Comment by NazagamerITA** [comment]
> sus

Enjoy

**Comment by bedantadey17** [comment]
close this
